import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Header from "@/components/header";
import { Suspense } from "react";
import Loading from "./page/loading";
import ProviderChakra from "@/components/Provider";
import Contact from "@/components/contact";
// import { ColorModeProvider } from "@/components/ui/color-mode";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Fidele Loffou Portoflio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container">
        <ProviderChakra>
          {/* <ColorModeProvider> */}
          <Suspense fallback={<Loading />}>
            <Header />
            {children}
            <Contact />
          </Suspense>
          {/* </ColorModeProvider> */}
        </ProviderChakra>
      </body>
    </html>
  );
}
